name: rkd-web-local

services:
  frontend:
    container_name: rkd-dockestra-web-local-1
    image: rkd-web-local-frontend:latest
    build: .
    restart: unless-stopped
    networks:
      rkd-local-network:
        aliases:
          - rkd-frontend

  nginx:
    container_name: nginx-local-1
    image: rkd-web-local-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy.local
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - rkd-local-network

networks:
  rkd-local-network:
    external: true
    name: rkd-local-network
